name: Deploy Sentinel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  LOCATION: uksouth
  RESOURCE_GROUP: rg-secops-uks   # change to your RG name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          region: ${{ env.LOCATION }}
          template: bicep/main.bicep
          parameters: >
            tenantId=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
            location=${{ env.LOCATION }}
