name: Deploy Sentinel + Azure Activity
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  LOCATION: uksouth
  RESOURCE_GROUP: rg-secops-uks

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create RG (idempotent)
      - name: Create resource group
        run: az group create -n "${{ env.RESOURCE_GROUP }}" -l "${{ env.LOCATION }}"

      # 1) RG-scope: deploy Sentinel (LAW + solution)
      - name: Deploy Sentinel (RG scope)
        id: rgdeploy
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          region: ${{ env.LOCATION }}
          template: bicep/main.bicep

      # 2) Sub-scope: route Azure Activity -> LAW using output from step 1
      - name: Enable Azure Activity (subscription scope)
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          region: ${{ env.LOCATION }}
          template: bicep/sub-azure-activity.bicep
          parameters: >
            lawResourceId=${{ fromJson(steps.rgdeploy.outputs.deploymentOutputs).workspaceId.value }}
