name: Deploy Sentinel (Bicep via SPN JSON)

on:
  workflow_dispatch:
    inputs:
      location:
        description: "Azure region for RG & deployment records"
        required: true
        default: "uksouth"
      resourceGroup:
        description: "Target resource group"
        required: true
        default: "rg-sentinel-demo"
      workspaceName:
        description: "Log Analytics workspace name"
        required: true
        default: "law-sentinel-demo"
      createWorkspace:
        description: "Create LAW if missing"
        required: true
        default: "true"
      retentionInDays:
        description: "LAW retention (30-730)"
        required: true
        default: "90"
      enableM365Defender:
        description: "Enable Microsoft 365 Defender connector"
        required: true
        default: "true"
      enableOffice365:
        description: "Enable Office 365 (ExO/SPO/Teams) connector (needs consent later)"
        required: true
        default: "false"
      enableThreatIntel:
        description: "Enable built-in Threat Intelligence connector"
        required: true
        default: "true"
      enableTaxii:
        description: "Enable TAXII connector"
        required: true
        default: "false"
      taxiiServer:
        description: "TAXII server URL"
        required: false
      taxiiCollectionId:
        description: "TAXII collection id"
        required: false
      taxiiUsername:
        description: "TAXII username"
        required: false
      taxiiPassword:
        description: "TAXII password (avoid plain text; use secrets)"
        required: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure context
        run: az account show -o table

      - name: Ensure resource group
        run: |
          az group create \
            -n "${{ github.event.inputs.resourceGroup }}" \
            -l "${{ github.event.inputs.location }}" -o none

      - name: Deploy RG scope (Workspace + Sentinel + dataConnectors)
        id: rgdeploy
        shell: bash
        env:
          TAXII_PASSWORD: ${{ github.event.inputs.taxiiPassword }}
        run: |
          set -euo pipefail

          PARAMS=(
            workspaceName="${{ github.event.inputs.workspaceName }}"
            createWorkspace=${{ github.event.inputs.createWorkspace }}
            retentionInDays=${{ github.event.inputs.retentionInDays }}
            enableM365Defender=${{ github.event.inputs.enableM365Defender }}
            enableOffice365=${{ github.event.inputs.enableOffice365 }}
            enableThreatIntel=${{ github.event.inputs.enableThreatIntel }}
            enableTaxii=${{ github.event.inputs.enableTaxii }}
            taxiiServer="${{ github.event.inputs.taxiiServer }}"
            taxiiCollectionId="${{ github.event.inputs.taxiiCollectionId }}"
            taxiiUsername="${{ github.event.inputs.taxiiUsername }}"
          )

          if [[ -n "${TAXII_PASSWORD:-}" ]]; then
            PARAMS+=(taxiiPassword="$TAXII_PASSWORD")
          fi

          az deployment group create \
            -g "${{ github.event.inputs.resourceGroup }}" \
            -f bicep/main.bicep \
            -p "${PARAMS[@]}" \
            -o json > rg_deploy.json

          WORKSPACE_ID=$(jq -r '.properties.outputs.workspaceIdOut.value' rg_deploy.json)
          echo "workspaceId=$WORKSPACE_ID" >> "$GITHUB_OUTPUT"
          echo "WorkspaceId: $WORKSPACE_ID"

      - name: Deploy subscription scope (Azure Activity → LAW)
        run: |
          az deployment sub create \
            -l "${{ github.event.inputs.location }}" \
            -f bicep/sub-azure-activity.bicep \
            -p workspaceId="${{ steps.rgdeploy.outputs.workspaceId }}" \
            -o table

      - name: Deploy tenant scope (Entra ID → LAW)
        run: |
          az deployment tenant create \
            -l "${{ github.event.inputs.location }}" \
            -f bicep/tenant-aad-logs-to-law.bicep \
            -p workspaceId="${{ steps.rgdeploy.outputs.workspaceId }}" \
            -o table
