name: Deploy Sentinel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  LOCATION: uksouth
  RESOURCE_GROUP: rg-secops-uks   # change if you want another RG

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group (idempotent)
        run: |
          az group create -n "${{ env.RESOURCE_GROUP }}" -l "${{ env.LOCATION }}"

      - uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          region: ${{ env.LOCATION }}
          template: bicep/main.bicep
