name: Deploy Sentinel (Bicep)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create RG if missing
        env:
          RG_NAME: rg-sentinel-demo      # change if you like
          AZ_LOCATION: uksouth           # change region if you like
        run: |
          az group create -n "$RG_NAME" -l "$AZ_LOCATION"

      - name: Deploy RG scope (Workspace + Sentinel)
        env:
          RG_NAME: rg-sentinel-demo
          AZ_LOCATION: uksouth
        run: |
          az deployment group create \
            --resource-group "$RG_NAME" \
            --template-file sentinel/bicep/main.bicep \
            --parameters location="$AZ_LOCATION" \
                         workspaceName="law-sentinel-${RG_NAME}" \
                         retentionDays=30 \
                         workspaceSku=PerGB2018 \
                         tags='{"env":"dev","iac":"bicep"}'
