name: Deploy Sentinel (Bicep, no createWorkspace)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Option A: deploy using the parameters file (recommended)
      - name: Deploy RG scope (Workspace + Sentinel)
        env:
          RG_NAME: rg-sentinel-demo          # <-- change if you like
        run: |
          az deployment group create \
            --resource-group "$RG_NAME" \
            --template-file bicep/main.bicep \
            --parameters @bicep/main.parameters.json

      # ---- Option B (alternative): pass params inline, no parameters file ----
      # - name: Deploy RG scope (inline params)
      #   env:
      #     RG_NAME: rg-sentinel-demo
      #     AZ_LOCATION: uksouth
      #   run: |
      #     az deployment group create \
      #       --resource-group "$RG_NAME" \
      #       --template-file bicep/main.bicep \
      #       --parameters location="$AZ_LOCATION" \
      #                    workspaceName="law-sentinel-${RG_NAME}" \
      #                    retentionDays=30 \
      #                    workspaceSku=PerGB2018
