name: Deploy Sentinel (Bicep via SPN JSON)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure context
        run: az account show -o table

      - name: Ensure resource group
        run: |
          az group create \
            -n rg-sentinel-demo \
            -l uksouth -o none

      - name: Deploy RG scope (Workspace + Sentinel + connectors)
        id: rgdeploy
        run: |
          set -euo pipefail
          az deployment group create \
            -g rg-sentinel-demo \
            -f bicep/main.bicep \
            -p workspaceName="law-sentinel-demo" \
               createWorkspace=true \
               retentionInDays=90 \
               enableM365Defender=true \
               enableOffice365=false \
               enableThreatIntel=true \
               enableTaxii=false \
            -o json > rg_deploy.json

          WORKSPACE_ID=$(jq -r '.properties.outputs.workspaceIdOut.value' rg_deploy.json)
          echo "workspaceId=$WORKSPACE_ID" >> "$GITHUB_OUTPUT"
          echo "WorkspaceId: $WORKSPACE_ID"

      - name: Deploy subscription scope (Azure Activity → LAW)
        run: |
          az deployment sub create \
            -l uksouth \
            -f bicep/sub-azure-activity.bicep \
            -p workspaceId="${{ steps.rgdeploy.outputs.workspaceId }}" \
            -o table

      - name: Deploy tenant scope (Entra ID → LAW)
        run: |
          az deployment tenant create \
            -l uksouth \
            -f bicep/tenant-aad-logs-to-law.bicep \
            -p workspaceId="${{ steps.rgdeploy.outputs.workspaceId }}" \
            -o table
