name: Deploy Microsoft Sentinel (Bicep)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  LOCATION: uksouth
  BASENAME: sec-law-uks

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ----- RG scope: LAW + Sentinel + (module) connectors
      - name: Deploy RG scope (main.bicep)
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          region: ${{ env.LOCATION }}
          template: bicep/main.bicep
          parameters: >
            location=${{ env.LOCATION }}
            baseName=${{ env.BASENAME }}

      # Get LAW ID for sub-scope deployment
      - name: Resolve LAW resource ID
        id: law
        run: |
          LAW_ID=$(az resource show \
            --resource-group "${{ secrets.RG_NAME }}" \
            --resource-type "Microsoft.OperationalInsights/workspaces" \
            --name "${{ env.BASENAME }}-law" \
            --query id -o tsv)
          echo "law_id=$LAW_ID" >> $GITHUB_OUTPUT
          echo "LAW_ID=$LAW_ID"

      # ----- Subscription scope: route Azure Activity to LAW (optional)
      - name: Deploy subscription scope (Azure Activity -> LAW)
        if: ${{ steps.law.outputs.law_id != '' }}
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          region: ${{ env.LOCATION }}
          template: bicep/sub-azure-activity.bicep
          parameters: >
            lawResourceId='${{ steps.law.outputs.law_id }}'
