name: Deploy Microsoft Sentinel (Bicep)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  LOCATION: uksouth
  BASENAME: sec-law-uks

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show context
        run: |
          az account show
          echo "RG_NAME=${{ secrets.RG_NAME }}"
          echo "LOCATION=$LOCATION"
          echo "BASENAME=$BASENAME"

      # ---------- RG-scope deployment (LAW + Sentinel + connectors)
      - name: Deploy RG-scope (main.bicep)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group "${{ secrets.RG_NAME }}" \
              --name "sentinel-rg-$(date +%Y%m%d%H%M%S)" \
              --template-file "bicep/main.bicep" \
              --parameters location="$LOCATION" baseName="$BASENAME"

      # Capture LAW resource ID as output (optional)
      - name: Get LAW resource ID
        id: get_law
        uses: azure/cli@v2
        with:
          inlineScript: |
            LAW_ID=$(az resource show \
              --resource-group "${{ secrets.RG_NAME }}" \
              --resource-type "Microsoft.OperationalInsights/workspaces" \
              --name "${BASENAME}-law" \
              --query id -o tsv)
            echo "law_id=$LAW_ID" >> $GITHUB_OUTPUT
            echo "LAW_ID=$LAW_ID"

      # ---------- Subscription-scope deployment (Azure Activity -> LAW) [optional]
      - name: Deploy subscription-scope (Azure Activity to LAW)
        if: ${{ steps.get_law.outputs.law_id != '' }}
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment sub create \
              --name "sentinel-sub-$(date +%Y%m%d%H%M%S)" \
              --location "$LOCATION" \
              --template-file "bicep/sub-azure-activity.bicep" \
              --parameters lawResourceId="${{ steps.get_law.outputs.law_id }}"
